#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Overall title for pages.
title: "Hands on brain dynamics on the connectome sinergia summer school: 2021 Oct 11-12"

# Repository URL (without trailing slash).
repo: https://github.com/sinergia-connectomics-summerschool-2021/scss21-training

# Root URL below username.github.io domain, with leading slash but no trailing slash.
# For example, for 'https://neurohackweek.github.io/lesson-example', use '/lesson-example'.
root: "/scss21-training"

# Contact email address.
email: sebastien.tourbier@alumni.epfl.ch

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Is this production or development? (Overridden in _config_dev.yml.)
is_production: true

# Sites.
nhw_site: "https://neurohackweek.github.io"
nhw_github: "https://github.com/neurohackweek"
swc_site: "https://software-carpentry.org"
scss21_site: "https://sinergia-connectomics-summerschool-2021.github.io/#intro"
template_repo: "https://github.com/swcarpentry/styles"
example_repo: "https://github.com/swcarpentry/lesson-example"
example_site: "https://swcarpentry.github.com/lesson-example"
rn_site: "https://repronim.github.io"
sc_site: "https://sinergiaconsortium.bitbucket.io/"
scss21_site: "https://sinergia-connectomics-summerschool-2021.github.io"
#rn_site: "https://repronim.org"
rn_github: "https://github.com/repronim"

# Start time in minutes (0 to be clock independent, 540 is 09:00 am)
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn off built-in syntax highlighting.
highlighter: rouge

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax
  math_engine_opts:
    preview: true   # not default but better accessibility

theme: jekyll-theme-leap-day
